[General]

; Show the item inspect menu when picking up quest items for the first time
bQuestItems = 1

; Show the item inspect menu when picking up unique items for the first time
bUniqueItems = 1


[Menu]

; Set camera type. 0 = Perspective, 1 = Orthographic
iCameraType = 0

; Display item name
bShowItemName = 1

; Display item stats
bShowItemStats = 1

; Display item description
bShowItemDescription = 1

; Display menu controls
bShowMenuControls = 1

; Display HUD while in the Item Inspect Menu
bShowHUD = 1


[Controls]

; Inspect item keybind. (Default: T)
; Key code list located here: https://geckwiki.com/index.php?title=IsKeyPressed
iKeyBind = 20

; Item rotation sensitivity multiplier (Mouse).
fSensitivityRotationMouse = 1

; Item rotation multiplier (Controller).
fSensitivityRotationController = 1

; Item zoom sensitivity multiplier (Mouse).
fSensitivityZoomMouse = 1

; Item zoom multiplier (Controller).
fSensitivityZoomController = 1

; Inertia friction multiplier.
fInertiaFriction = 1
